# Generated by Django 5.1.3 on 2024-11-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='juego1',
            new_name='palabras',
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='juego2',
            new_name='quiz',
        ),
    ]
