# Generated by Django 5.1.3 on 2024-11-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0003_remove_puntuacion_palabras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
