# Generated by Django 5.1.3 on 2024-11-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0004_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='username',
        ),
        migrations.AddField(
            model_name='administrador',
            name='usser',
            field=models.CharField(default='default_user', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
