# Generated by Django 5.1.3 on 2024-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0005_remove_administrador_username_administrador_usser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='usser',
        ),
        migrations.AddField(
            model_name='administrador',
            name='username',
            field=models.CharField(default='defaul_user', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
