# Generated by Django 5.1.3 on 2024-11-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0006_remove_administrador_usser_administrador_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
