# Generated by Django 5.1.3 on 2024-11-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0007_delete_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='correctas',
            field=models.IntegerField(default=0),
        ),
    ]
