# Generated by Django 5.1.3 on 2024-11-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0008_puntuacion_correctas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='correctas',
        ),
    ]
