# Generated by Django 5.1.3 on 2024-11-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0001_initial'),
        ('app_juegos', '0009_remove_puntuacion_correctas'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_juegos.usuario'),
            preserve_default=False,
        ),
    ]
