# Generated by Django 5.1.3 on 2024-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0002_respuesta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tiempo_respuesta',
            field=models.FloatField(default=0),
        ),
    ]
